from __future__ import annotations

from textwrap import dedent

from ..models import Artifact, TaskSpec


class CoderAgent:
    name = "coder"

    def run(self, task: TaskSpec, plan: Artifact) -> Artifact:
        stack_hint = ", ".join(task.stack) if task.stack else "Python stdlib"
        code = dedent(
            f"""
            \"\"\"Auto-generated solution draft.
            Task: {task.title}
            Stack hint: {stack_hint}
            \"\"\"

            from dataclasses import dataclass
            from typing import Any


            @dataclass
            class Request:
                payload: dict[str, Any]


            @dataclass
            class Response:
                ok: bool
                data: dict[str, Any]
                message: str = ""


            def execute(request: Request) -> Response:
                \"\"\"Core execution path generated by CoderAgent.

                Replace this logic with domain-specific implementation.
                \"\"\"
                if not isinstance(request.payload, dict):
                    return Response(ok=False, data={{}}, message="payload must be a dict")

                # Placeholder business logic. In production, isolate side effects and add observability.
                result = {{
                    "received_keys": sorted(request.payload.keys()),
                    "item_count": len(request.payload),
                }}
                return Response(ok=True, data=result)
            """
        ).strip() + "\n"

        return Artifact(
            name="01_solution.py",
            content=code,
            metadata={"agent": self.name, "based_on": plan.name},
        )

